title: "Gabriel Aplok"
tagline: "Pixel Artist and Game Producer."
description: "Come check some of my work."
icon: /assets/images/icon.png
lang: en-US

email: "gabrielaplok.contact@gmail.com"
twitter: "https://twitter.com/GabrielAplok"
youtube: "https://youtube.com/GabrielAplok"
instagram: "https://instagram.com/gabriel__yeah"
discord: "https://discord.gg/PppEgBdss4"

author:
  name: "Gabriel Aplok"
  email: "gabrielaplok.contact@gmail.com"
  url: "https://gabriel-aplok.github.io"

plugins:
  - jekyll-sitemap

collections:
  news:
    output: true
  articles:
    output: true
  projects:
    output: true
