title: Gabriel Aplok
tagline: Full-Stack Developer| Minecraft Bedrock Addon Developer.
description: Come check some of my work.
icon: /assets/img/icon.png
logo: /assets/img/logo.png
timezone: America/New_York
lang: en-US
url: https://gabriel-aplok.com

google_analytics: G-FJD9RTYZP5
issues_repo: gabriel-aplok/gabriel-aplok.github.io

email: gabrielaplok.contact@gmail.com
x: https://x.com/GabrielAplok
youtube: https://youtube.com/GabrielAplok
github: https://github.com/gabriel-aplok/
itchio: https://gabriel-aplok.itch.io/
discord: https://discord.gg/PppEgBdss4

markdown: kramdown
kramdown:
  input: GFM

author:
  name: Gabriel Aplok
  email: gabrielaplok.contact@gmail.com
  url: https://gabriel-aplok.github.io

plugins:
  - jekyll-minifier
  - jekyll-sitemap

jekyll-minifier:
  exclude: atom.xml
  uglifier_args:
    harmony: true
    
collections:
  blog:
    output: true
  projects:
    output: true

webrick:
  headers:
    FireWave-Service-Id: e2674490bdb54c76836073fa6299e53d
