title: Gabriel Aplok
tagline: Full-Stack Developer | Game Developer.
description: Come check some of my work.
url: https://gabriel-aplok.com
api_url: https://api.gabriel-aplok.com/api
baseurl: ""

icon: /assets/img/icon.png
logo: /assets/img/logo.png
avatar: /assets/img/profile.png

timezone: America/Sao_Paulo
lang: en-US
build_revision: 4

social:
  name: Gabriel Aplok
  email: contact@gabriel-aplok.com
  links:
    - https://gabriel-aplok.com

google_site_verification: 6KdYh_ff3c8RKaXlzqEcnUscw98UzP8rjM6tXFr-qPQ
google_tagmanager: GTM-MJSM745

issues_repo: gabriel-aplok/gabriel-aplok.github.io

email: contact@gabriel-aplok.com
x: https://x.com/GabrielAplok
youtube: https://youtube.com/GabrielAplok
github: https://github.com/gabriel-aplok/
itchio: https://gabriel-aplok.itch.io/
discord: https://discord.gg/PppEgBdss4

plugins:
  - jekyll-sitemap

markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    css_class: highlight

collections:
  projects:
    output: true

sass:
  style: compressed

compress_html:
  clippings: all
  comments: all
  endings: all
  profile: false
  blanklines: false
  ignore:
    envs: [development]

exclude:
  - "*.gem"
  - "*.gemspec"
  - README.md
  - LICENSE
  - package.json

warn_content_creator: >
  If you plan to showcase this content, <strong>ONLY use the links I provide here</strong>. DON’T create your own links and/or claim this as your own creation. Thank you!
warn_install_addon: >
  Open the **.mcpack** with **Minecraft** and automatically import or extract and copy manually the folder to behavior and resources in the respective Minecraft folders.
warn_install_world: >
  Open the **.mcworld** with **Minecraft** and automatically import or extract and copy manually the folder to the respective Minecraft worlds folders.
